# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docelement_file.proto
# Protobuf Python Version: 4.26.0-dev
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wordelement_file_pb2 as wordelement__file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64ocelement_file.proto\x1a\x16wordelement_file.proto\"i\n\nDocElement\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12!\n\x0bwordelement\x18\x04 \x03(\x0b\x32\x0c.WordElement\x12\x0b\n\x03url\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'docelement_file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCELEMENT']._serialized_start=49
  _globals['_DOCELEMENT']._serialized_end=154
# @@protoc_insertion_point(module_scope)
