# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forwardindex_file.proto
# Protobuf Python Version: 4.26.0-dev
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import docelement_file_pb2 as docelement__file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66orwardindex_file.proto\x1a\x15\x64ocelement_file.proto\"/\n\x0c\x46orwardIndex\x12\x1f\n\ndocelement\x18\x01 \x03(\x0b\x32\x0b.DocElementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forwardindex_file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDINDEX']._serialized_start=50
  _globals['_FORWARDINDEX']._serialized_end=97
# @@protoc_insertion_point(module_scope)
